# Generated by Django 3.2.7 on 2021-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210912_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtor',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы '},
        ),
        migrations.AlterField(
            model_name='books',
            name='publishings',
            field=models.ManyToManyField(blank=True, related_name='book_publishing', to='books.Publishing', verbose_name='Издательства'),
        ),
    ]
