# Generated by Django 3.2.7 on 2021-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210912_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Страна')),
                ('image', models.ImageField(blank=True, upload_to='country/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='country',
        ),
        migrations.AddField(
            model_name='book',
            name='countrys',
            field=models.ManyToManyField(blank=True, max_length=50, related_name='book_country', to='books.Country', verbose_name='Страна'),
        ),
    ]
